InsteadOfTrigger:
	Will be run on view.
	
Scenario:

Table: EMP
Table: Dept

Below view create statement creates view by using both EMP and Dept table:

CREATE OR REPLACE VIEW EMP_DEPT_VS AS
SELECT E.EMPNO,E.ENAME,E.JOB,E.MGR,E.HIREDATE,E.SAL,E.DEPTNO,D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO;

When trying to insert below insert statement on view Oracle will through an error:

INSERT INTO EMP_DEPT_VW(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,DEPTNO,DNAME) VALUES
(1000,'SIVA','TRAINER',7839,'14-FEB-2025',1000,50,'R AND D');

Simple View: One table is base, view is created based on one table.

CREATE OR REPLACE TRIGGER TRIGGER_NAME_VW
INSTEAD OF INSERT ON EMP_DEPT_VS
DECLARE
LV_CHECK_EXIST NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO LV_CHECK_EXIST
	FROM DEPT WHERE DEPTNO=:NEW.DEPTNO;
	
	IF LV_CHECK_EXIST =0 THEN
		INSERT INTO DEPT(DEPTNO,DNAME)
		VALUES(:NEW.DEPTNO,:NEW.DNAME);
	END IF;
	
	SELECT COUNT(*)
	INTO LV_CHECK_EXIST
	FROM EMP WHERE EMPNO=:NEW.EMPNO;
	
	IF LV_CHECK_EXIST =0 THEN
		INSERT INTO EMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,DEPTNO)
		VALUES(:NEW.EMPNO,:NEW.ENAME,:NEW.JOB,:NEW.MGR,:NEW.HIREDATE,:NEW.SAL,:NEW.DEPTNO);
	END IF;

END TRIGGER_NAME_VW;
/

Now if we issue below insert statement record will be inserted into emp and dept table.

INSERT INTO EMP_DEPT_VW(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,DEPTNO,DNAME) VALUES
(1000,'SIVA','TRAINER',7839,'14-FEB-2025',1000,50,'R AND D');
