ReverseKeyIndex:
B-Tree index type, just reverse the key value and stores in index.

Advantage:
Index block contention.(More number of records are part of  a block)
After index field is reversed value will be distributed equally and stored.


Disadvantage:
Index Range scan cannot be performed. As records are not sorted in reverse key index range scan is not possible instead oracle will go for full scan.
SELECT * FROM STUDENT WHERE SCORE >90;

CREATE INDEX INDEX_NAME ON STUDENT(MARK) REVERSE;

Below index is normal b-tree index where we created index on Mark.  

RowID					Mark
ROWIDFORTHISFIELDIS1	95
ROWIDFORTHISFIELDIS2	77
ROWIDFORTHISFIELDIS3	32		
ROWIDFORTHISFIELDIS4	24
ROWIDFORTHISFIELDIS5	73
ROWIDFORTHISFIELDIS6	88
ROWIDFORTHISFIELDIS7	12
ROWIDFORTHISFIELDIS8	31
ROWIDFORTHISFIELDIS9	94
ROWIDFORTHISFIELDIS10	97

Data will be stored like below.

mark from 76-100
ROWIDFORTHISFIELDIS1	95
ROWIDFORTHISFIELDIS2	77
ROWIDFORTHISFIELDIS6	88
ROWIDFORTHISFIELDIS9	94
ROWIDFORTHISFIELDIS10	97

mark from 51-75
ROWIDFORTHISFIELDIS5	73

mark from 26-50
ROWIDFORTHISFIELDIS3	32
ROWIDFORTHISFIELDIS8	31

mark from 1-25
ROWIDFORTHISFIELDIS4	24
ROWIDFORTHISFIELDIS7	12

if you see above index is not equally distributed. but if we go with reverse index this will be solved.

RowID					Mark
ROWIDFORTHISFIELDIS1	59
ROWIDFORTHISFIELDIS2	77
ROWIDFORTHISFIELDIS3	23		
ROWIDFORTHISFIELDIS4	42
ROWIDFORTHISFIELDIS5	37
ROWIDFORTHISFIELDIS6	88
ROWIDFORTHISFIELDIS7	21
ROWIDFORTHISFIELDIS8	13
ROWIDFORTHISFIELDIS9	49
ROWIDFORTHISFIELDIS10	79

mark from 76-100
ROWIDFORTHISFIELDIS2	77
ROWIDFORTHISFIELDIS6	88
ROWIDFORTHISFIELDIS10	79

mark from 51-75
ROWIDFORTHISFIELDIS1	59

mark from 26-50
ROWIDFORTHISFIELDIS4	42
ROWIDFORTHISFIELDIS5	37
ROWIDFORTHISFIELDIS9	49

mark from 1-25
ROWIDFORTHISFIELDIS3	23
ROWIDFORTHISFIELDIS7	21
ROWIDFORTHISFIELDIS8	13
